apiVersion: v1
kind: Service
metadata:
  name: nurapp-service
  labels:
    app: nurapp
spec:
  type: LoadBalancer  # Exposes the service externally via a cloud load balancer
  ports:
  - port: 80          # External port
    targetPort: 80    # Port on the container
  selector:
    app: nurapp